apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: {{ include "bootcamp-e2e.fullname" . }}
  labels:
    {{- include "bootcamp-e2e.labels" . | nindent 4 }}
spec:
  port:
    targetPort: http
  to:
    kind: Service
    name: {{ include "bootcamp-e2e.fullname" . }}
